### ISSUE TITLE
Util fn to map attr to React equivalent

### ISSUE THREAD

**Issue by sdgluck** [jackyho112/react-html-attributes#8]
I am writing a parser that builds a React component tree from an HTML string. I have slowly been adding to a map of html attribute names to their React counterparts. It would be nice not to have to do this manually, and I stumbled across this library which gives us all the React attribute names, but not what their "native" names are.

Would a utility function that maps an attribute name to its React equivalent be something that you would be interested in adding to this library?

e.g.

    toReactAttribute('allowfullscreen')
    //=> 'allowFullScreen'

Cheers

**Comment by jackyho112** [comment]
Thanks for your suggestion! I will look into it over the weekend!

**Comment by jackyho112** [comment]
@sdgluck 

Sorry, I could not find a way to do it with 100% correctness by not hardcoding too much. If you know a library or a site I could use to transform an HTML attribute into a React component attribute, let me know. Otherwise, I don't think I will support this feature for now. Sorry about that. 😥
